import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarMenu from "./_components/sidebar";

export const metadata: Metadata = {
  title: "Stockly",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full gap-8">
          <SidebarMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
